### ISSUE TITLE
Specialty Bearer Token Authentication

### ISSUE THREAD

**Issue by crast** [pdarg/tmlpstats#18]
Allow delegation with a random-ish code that is generated

**Comment by pdarg** [comment]
Pull request #174 get's us a step closer to this goal.

The next steps are to come up with a way to represent a report-only user using an authenticated user, then add authorization rules matching that user up with their code.

Also, we'll need to add a db that maps these tokens to a report

**Comment by pdarg** [comment]
Pull request #180 fully implemented this. There are a number of enhancements that came in separate pull requests later.
